/**
 * AddDeviceTableViewController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface AddDeviceTableViewController : UITableViewController <CBCentralManagerDelegate,UIControl$OnValueChangedListener>

@end
