/**
 * BLEDataView.m
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

#import "BLEDataView.h"

@interface j_com_liferay_bluetooth_BLEDataView ()

@end
