/**
 * DeviceDataUIView.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface j_com_liferay_bluetooth_DeviceDataUIView : UIView 

@end
