/**
 * MainViewController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface MainViewController : UIViewController <CBCentralManagerDelegate,CBPeripheralDelegate>

/**
 * IBOutlet bleDataView
 */
@property (weak, nonatomic) IBOutlet UIScrollView *bleDataView;

/**
 * IBAction onClickAddDevice
 * Selector: onClickAddDevice
 */
-(IBAction) onClickAddDevice;

@end
