/**
 * ScanBLEDeviceViewController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface ScanBLEDeviceViewController : UITableViewController <CBCentralManagerDelegate,UIControl$OnValueChangedListener>

@end
